services:
  kayumars-bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: kayumars-bot
    environment:
      BOT_TOKEN: ${BOT_TOKEN}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    volumes:
      - ./config.yml:/build/config.yml